// <auto-generated />
using System;
using DevTestes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevTestes.Migrations
{
    [DbContext(typeof(DevTestesContext))]
    partial class DevTestesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevTestes.Models.BugProblema", b =>
                {
                    b.Property<int>("BugProblemaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Chamado")
                        .HasColumnName("varchar(6)");

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("DtaComplemento");

                    b.Property<string>("Funcionario")
                        .HasColumnName("varchar(30)");

                    b.Property<string>("Impacto");

                    b.Property<string>("Produto")
                        .HasColumnName("varchar(20)");

                    b.Property<string>("Sprint")
                        .HasColumnName("varchar(20)");

                    b.HasKey("BugProblemaId");

                    b.ToTable("BugProblemas");
                });

            modelBuilder.Entity("DevTestes.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnName("varchar(20)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("DevTestes.Models.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeSprint")
                        .IsRequired()
                        .HasColumnName("varchar(20)");

                    b.HasKey("SprintId");

                    b.ToTable("Sprints");
                });
#pragma warning restore 612, 618
        }
    }
}
